export type User = {
  id: string;
  name: string;
  email: string;
  phone: string;
  points: number;
  avatar: string;
};
export type Cafe = {
  id: string;
  owner_id: string | null;
  name: string;
  description: string;
  city: string;
  address: string;
  phone: string;
  image: string;
  amenities: string[];
  latitude: number | null;
  longitude: number | null;
  opens: string;
  closes: string;
  capacity: number;
  delivery: boolean;
  pickup: boolean;
  delivery_fee: number;
  active: boolean;
  source: string;
  rating: number | null;
  review_count: number;
};
export type Option = { id: string; name: string; price: number };
export type Product = {
  id: string;
  cafe_id: string;
  cafe_name?: string;
  name: string;
  description: string;
  category: string;
  price: number;
  image: string;
  available: boolean;
  sizes: Option[];
  addons: Option[];
  max_addons: number;
  source: string;
};
export type Address = {
  id: string;
  title: string;
  city: string;
  street: string;
  postal_code: string;
  receiver: string;
  phone: string;
  latitude: number | null;
  longitude: number | null;
  is_default: boolean;
};
export type CartLine = {
  key: string;
  product_id: string;
  cafe_id: string;
  name: string;
  image: string;
  price: number;
  size_id: string;
  addon_ids: string[];
  option_names: string[];
  quantity: number;
  note: string;
};
export type Order = {
  id: string;
  user_id: string;
  cafe_id: string;
  cafe_name: string;
  customer_name?: string;
  mode: 'delivery' | 'pickup';
  status: string;
  items: CartLine[];
  subtotal: number;
  discount: number;
  delivery_fee: number;
  points_used: number;
  total: number;
  address: Address | null;
  pickup_at: string;
  note: string;
  created_at: string;
  updated_at: string;
};
export type Reservation = {
  id: string;
  cafe_id: string;
  cafe_name: string;
  user_id: string;
  customer_name?: string;
  date: string;
  time: string;
  guests: number;
  note: string;
  status: string;
  created_at: string;
};
export type CafeEvent = {
  id: string;
  cafe_id: string;
  cafe_name: string;
  title: string;
  description: string;
  date: string;
  time: string;
  capacity: number;
  image: string;
  registered: number;
  joined: boolean;
};
export type Review = { id: string; name: string; rating: number; body: string; created_at: string };
export type Coupon = {
  id: string;
  cafe_id: string;
  code: string;
  percent: number;
  expires: string;
  max_uses: number;
  uses: number;
};
export type Notice = {
  id: string;
  title: string;
  body: string;
  href: string;
  read: boolean;
  created_at: string;
};
export type Ticket = {
  id: string;
  subject: string;
  body: string;
  order_id: string;
  status: string;
  created_at: string;
  replies: { id: string; body: string; created_at: string; name: string }[];
};
export type Bootstrap = {
  user: User | null;
  cafes: Cafe[];
  products: Product[];
  events: CafeEvent[];
  favorites: string[];
  rewards: { cafe_id: string; cafe_name: string; points: number }[];
  notifications: Notice[];
  smsAvailable: boolean;
  mailAvailable: boolean;
};
